# 闯关题1

In [1]:
import numpy as np
import pandas as pd

np.random.seed(123)

## STEP1：生成被试编号  
1. 生成100个被试编号，格式为"sub_xx"，如sub_01，sub_02...sub_100  
2. 从其中选取编号为奇数的被试，如sub_01, sub_03,...sub_99  
3. 将结果存为sub_array  

    注：可参考教程中的代码

In [2]:
sub_array = [f"sub{i:02}" for i in range(1,101)]

In [3]:
sub_array = sub_array[::2]

## STEP2：生成不同条件下的反应时  
1. 生成50个条件A下的反应时，条件A下的反应时服从均值为350，标准差为25的正态分布，变量名存为“rt_A”  
2. 生成50个条件B下的反应时，条件B下的反应时服从均值为450，标准差为35的正态分布，变量名存为“rt_B”  
3. 计算条件A与条件B反应时的差值(条件B减去条件A)，变量名存为“rt_diff”  
* 注：将所有生成的反应时存为整数

In [4]:
rt_A = np.random.normal(loc = 350,
                 scale = 25,
                 size = 50)
rt_A = rt_A.astype(int)

In [5]:
rt_B = np.random.normal(loc = 450,
                 scale = 35,
                 size = 50)
rt_B = rt_B.astype(int)

In [6]:
rt_diff = rt_B - rt_A
rt_diff = rt_diff.astype(int)

## STEP3：转为数据框  
1. 将被试编号、条件A、B的反应时，与二者差值存在同一个数据框中  
2. 列名分别为：sub_ID，rt_A，rt_B，rt_diff  
3. 数据框命名为df_rt  
4. 选取rt_diff 列的前10个值，存入变量a1中

In [7]:
df_rt = pd.DataFrame({'sub_ID': sub_array,
                      'rt_A': rt_A, 
                      'rt_B': rt_B, 
                      'rt_diff': rt_diff})

In [8]:
df_rt

   sub_ID  rt_A  rt_B  rt_diff
0   sub01   322   404       82
1   sub03   374   413       39
2   sub05   357   511      154
3   sub07   312   422      110
4   sub09   335   451      116
5   sub11   391   487       96
6   sub13   289   481      192
7   sub15   339   511      172
8   sub17   381   502      121
9   sub19   328   487      159
10  sub21   333   422       89
11  sub23   347   477      130
12  sub25   387   460       73
13  sub27   334   403       69
14  sub29   338   499      161
15  sub31   339   478      139
16  sub33   405   451       46
17  sub35   404   441       37
18  sub37   375   408       33
19  sub39   359   456       97
20  sub41   368   466       98
21  sub43   387   420       33
22  sub45   326   490      164
23  sub47   379   411       32
24  sub49   318   375       57
25  sub51   334   486      152
26  sub53   372   435       63
27  sub55   314   445      131
28  sub57   346   420       74
29  sub59   328   393       65
30  sub61   343   493      150
31  sub63   280   425      145
32  sub65   305   508      203
33  sub67   332   478      146
34  sub69   373   438       65
35  sub71   345   411       66
36  sub73   350   424       74
37  sub75   367   407       40
38  sub77   328   523      195
39  sub79   357   455       98
40  sub81   329   490      161
41  sub83   306   405       99
42  sub85   340   456      116
43  sub87   364   491      127
44  sub89   358   438       80
45  sub91   349   486      137
46  sub93   409   412        3
47  sub95   360   402       42
48  sub97   374   463       89
49  sub99   405   436       31

In [9]:
a1 = df_rt['rt_diff'][0:10]

In [10]:
a1

0     82
1     39
2    154
3    110
4    116
5     96
6    192
7    172
8    121
9    159
Name: rt_diff, dtype: int64


------------  

## STEP4：绘制泊松分布图  

假设你是一个up主，过去这一年，你发布视频获得的点赞数一般在20-160之间，平均每一周会有100个人给你的视频点赞。  

请你根据现有的数据，绘制点赞人数概率的泊松分布图，并回答下列问题，将答案填入下方代码cell中对应的变量内。  

>**问题Q1：假设事件A为平均一周有60人给你的视频点赞，事件A发生的概率大约是：  
> A.0%  
> B.2%  
> C.4%**  

步骤参考：  
1. 生成横坐标数据：点赞数(可参考题目中的点赞数范围)  
2. 使用scipy中的 st.poisson.pmf() 来生成对应的概率数据  
3. 绘图(提示：seaborn中接受的数据格式为数据框类型，可以选择转化为数据框后再绘图，或使用matplotlib.pyplot进行绘图)

In [11]:
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
x = np.arange(20,161,1)
mu = 100
plt.stem(x,st.poisson.pmf(x,mu))

In [12]:
a2 = 'A'  # 在''中间填写你的 Q1 选项

## STEP5：将结果保存为 csv 文件  
💡 这一步的代码你无需修改，直接运行即可。

In [13]:
# 运行这两个cell,生成答案文件；
# 该文件在左侧文件树project工作区下，你可以自行右击下载或者读取查看

a1 = a1.to_list()

answer = pd.DataFrame({"id": ["q1", "q2"],
                        "answer": [a1,a2]})

answer.to_csv("answer_1.csv", index=None)

In [14]:
answer

   id                                           answer
0  q1  [82, 39, 154, 110, 116, 96, 192, 172, 121, 159]
1  q2                                                A